[package]
authors = ["Jonathan Creekmore <jonathan@thecreekmores.org>"]
name = "bootinfo"
version = "0.1.0"
license = "Apache-2.0/MIT"
readme = "README.md"
categories = ["development-tools"]

[dependencies]
bitflags = "1.0.1"
bytes = "0.4.6"
derive-error-chain = "0.11.0"
error-chain = "0.11.0"
flate2 = "1.0.1"
structopt = "0.1.6"
structopt-derive = "0.1.6"
